### ISSUE TITLE
Liquid animation freezes until view disappears and reappears.

### ISSUE THREAD

**Issue by haroutig** [maustinstar/liquid#2]
I'm not 100% certain why this is occurring, and it may be something to do with my code, but whenever I update a variable in my app, triggering a change in my view, within a second the animation for Liquid freezes. It only resumes whenever i leave the view and reenter.

![Screen Recording 2020-09-24 at 9 52 24 PM](https://user-images.githubusercontent.com/42183391/94217733-bdc93200-feb0-11ea-9a91-3dee889f650b.gif)

**Comment by haroutig** [comment]
It seems to only happen when updating the variable tracking progress through an environment object. I'm guessing it has to do with blocking the thread on which the timer for the animation is running, causing it to not continue the animation.

**Comment by maustinstar** [comment]
Can you post a code snippet to replicate this behavior on my end?

**Comment by haroutig** [comment]
Alright I may have found the issue when creating a stripped down test version of my app to demonstrate the bug. In my app I was passing the value to a var in my new view rather than passing my model as an EnvironmentObject. For some reason this caused Swift to pause the animation. I'm not entirely sure why this behaviour occurs and it may be a bug in swift, but for now this issue can be closed.

**Comment by haroutig** [comment]
I think i found where the problem was, it seems that when using a variable in the new view rather than passing an environmentobject and reading directly from that, swift pauses animations until you retrigger them (in this case, leaving the view and coming back). No idea why this happens, may be a bug in swift or something i was doing wrong...
